### ISSUE TITLE
We aim for a completed website with peppol ?

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/peppol-python-demo#1]
If yes:
          We must think about :

          1) Database ​
         ​ 2) API 
         ​ 3) Frontend 
         ​ 4) Backend 
          5) Which parts will be opensource ( security reasons)

**Comment by michielbdejong** [comment]
I'll move this issue to https://github.com/pondersource/peppol-python-demo so we can implement this part of the project there.

**Comment by michielbdejong** [comment]
I think we can we close this issue now?
