### ISSUE TITLE
"This account is not active."

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-python-demo#17]
I created a user 'michielbejong2' / 'michiel+2@pondersource.com' but when I try to log in at http://demo.pondersource.net/accounts/log-in/ it says the account is not active. I'll see if I can poke it in the database :)

**Comment by michielbdejong** [comment]
```sql
df7lhksho569vn=> update auth_user set is_active=True;
UPDATE 2
```
That worked!

**Comment by michielbdejong** [comment]
We can use this work-around for now, until #12.

**Comment by Felicia-Doumani** [comment]
In which file should I add these 2 lines of code? settings.py?

**Comment by michielbdejong** [comment]
First, find out the postgres database URL. You can find it on https://dashboard.heroku.com/apps/demo-pondersource-net/settings ('Reveal Config Vars'). I'll also Slack it to you.
Then you make sure you have `psql` installed (the client for Postgres), and type `psql <database URL>` in your laptop terminal. It will open an SQL session with the Postgres database on our live Heroku app.
Then you can type SQL statements like `SELECT * FROM auth_user`.
