### ISSUE TITLE
Untranslated strings when you change the language

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/peppol-python-demo#19]

**Comment by michielbdejong** [comment]
We should pick a few languages and do the translations.

**Comment by michielbdejong** [comment]
But let's do this after we finish the (first) GUI design so we know which strings to translate.

**Comment by Felicia-Doumani** [comment]
Include for sure all the languages ​​spoken in countries that use Peppol and then add more.

**Comment by Felicia-Doumani** [comment]
on content/locale/*/LC_MESSAGES/django.po

**Comment by Felicia-Doumani** [comment]
Only English for the demo.
