### ISSUE TITLE
NoReverseMatch at /django_messages/outbox/  Reverse for 'messages_detail' not found. 'messages_detail' is not a valid view function or pattern name.

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/peppol-python-demo#29]

**Comment by michielbdejong** [comment]
This is on the `invoice` branch.

**Comment by michielbdejong** [comment]
On line 85 of  django_messages/models.py
I think if you merge #33 and change that to `return reverse('django_messages:messages_detail', args=[self.id])` it should work
