### ISSUE TITLE
Show various icons in messages list and in "compose message"

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-python-demo#60]
When a message was user-to-user, from/to Peppol, or from/to ebMS+WebID, or just imported from the bookkeeping system, we should display different icons.

**Comment by Felicia-Doumani** [comment]
For now, we use different colors instead of icons (green for when it is in our trusted contacts, otherwise orange). Other identifiers must be added in addition to the color because it is not always helpful (cases of color blindness)

**Comment by michielbdejong** [comment]
* is this user in your contacts?
* is the `is_supplier` field set?
* is the `is_customer` field set?
* is this user verified?
* Add in sprint 3: was this message sent via Peppol Direct or via Peppol Classic? (see https://github.com/pondersource/peppol-python-demo/issues/93)
