### ISSUE TITLE
Send direct messages through a SOAP server 

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/peppol-python-demo#61]
Modify the existing Django-messages implementation.

To achieve this we need to change the structure of the Message model to an XML file because the only way a SOAP server communicates with a SOAP client is through XML files.

I'm looking for a way to avoid converting to XML, but I think it's the only way if we want to include all the information we want (sender/receiver/subject/body, etc.).

**Comment by michielbdejong** [comment]
Right! But XML can contain plain text. This may help:
https://stackoverflow.com/questions/32259079/converting-non-xml-to-xml-or-soap-using-xslt-1-0
https://www.cleo.com/blog/soap-worst-practices-part-1-non-xml-content
