### ISSUE TITLE
if message body starts with '<?xml', offer a "download" button

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-python-demo#65]
in the inbox view

**Comment by Felicia-Doumani** [comment]
When you send a message you can : 

- Write a direct message 

- Upload an invoice

So, I tried this:

Τhe 'download' button only appears when the sender has sent an invoice, so it is not an "if message body starts with '<?xml' " implementation.
What do you think?

**Comment by michielbdejong** [comment]
Ah yes, great!
