### ISSUE TITLE
IntegrityError at /accounts/sign-up/ duplicate key value violates unique constraint "auth_user_username_key" DETAIL:  Key (username)=() already exists.

### ISSUE THREAD

**Issue by Felicia-Doumani** [pondersource/peppol-python-demo#69]

**Comment by Felicia-Doumani** [comment]
Error after sign up on demo-pondersource-net

**Comment by michielbdejong** [comment]
That means you tried to insert a row in the database that has the same username as a row that is already there. Normally Django should catch 'that username is already taken', but apparently here Django tried to execute the SQL 'INSERT' query and it failed at the database level.
