### ISSUE TITLE
Add __pycache__ to .gitignore

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-python-demo#8]

**Comment by michielbdejong** [comment]
https://stackoverflow.com/questions/3719243/best-practices-for-adding-gitignore-file-for-python-projects says to add `*.pyc`, I think that would have the same effect

**Comment by michielbdejong** [comment]
What is the admin password when you first set it up? Does the first user to register become an admin?

**Comment by Felicia-Doumani** [comment]
you have to execute: **python manage.py createsuperuser** and generate a superuser first

**Comment by michielbdejong** [comment]
ah thanks!

**Comment by michielbdejong** [comment]
Fixed in #14
